name: courtwala
description: A sports booking app for badminton, padel, cricket, and football courts.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  js: ^0.7.1
  google_sign_in: ^6.1.5
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.12.0
  fl_chart: ^1.1.1
  image_picker: ^1.1.1
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/court_wala_logo.png
    - assets/Court.png
    - assets/carousel1.jpg
    - assets/carousel2.jpg
    - assets/carousel3.webp
    - assets/badmintonCourt.jpeg