name: courtwala
description: A sports booking app for badminton, padel, cricket, and football courts.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.23.0       # latest null-safe version
  firebase_auth: ^4.7.0        # latest null-safe version
  js: ^0.7.2
  google_sign_in: ^6.1.5
  carousel_slider: ^5.1.0
  font_awesome_flutter: ^10.4.0
  fl_chart: ^1.1.1
  image_picker: ^1.1.1
  intl: ^0.18.1
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/court_wala_logo.png
    - assets/Court.png
    - assets/carousel1.jpg
    - assets/carousel2.jpg
    - assets/carousel3.webp
    - assets/badmintonCourt.jpeg
